gateway:
  auth:
    type: jupyterhub
    jupyterhub:
      apiTokenFromSecretName: hub
      apiTokenFromSecretKey: hub.services.dask-gateway.apiToken
  prefix: /services/dask-gateway
  extraConfig:
    resource-limits: |
      c.ClusterConfig.cluster_max_cores = 16
      c.ClusterConfig.cluster_max_memory = "32 G"
      c.ClusterConfig.idle_timeout = 3600
  backend:
    image:
      name: pangeo/pangeo-notebook
      tag: "2025.05.22"
    scheduler:
      cores:
        request: 0.5
        limit: 1
      memory:
        request: "1G"
        limit: "2G"
      extraPodConfig:
        nodeSelector:
          hub.jupyter.org/node-purpose: user
    worker:
      cores:
        request: 2
        limit: 4
      memory:
        request: "4G"
        limit: "8G"
      extraPodConfig:
        nodeSelector:
          hub.jupyter.org/node-purpose: user

traefik:
  image:
    name: traefik
    tag: "3.3.5"
  service:
    type: LoadBalancer
