channels:
  - conda-forge

dependencies:
  - cdshealpix
  - healpy
  - h3ronpy
  - xdggs
  - pip
  - pip:
      - git+https://github.com/EOPF-DGGS/healpix-geo.git
      - git+https://github.com/EOPF-DGGS/healpix-plot.git
      - git+https://github.com/EOPF-DGGS/healpix-resample.git
